#开启调试日志
#logging:
#  level: org.springframework= INFO

#关闭jndi
#spring.jndi.ignore=true

#关闭 默认模板
#spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=false

uploadAbsolutePath: C:/mySource

# 驱动配置信息
spring:
  datasource:
    druid:
      #监控:统计拦截的filters
      filters: stat
      url: jdbc:mysql://localhost:3306/hpedu?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  # 页面默认前缀目录
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
server:
  port: 8082
  servlet:
    path: /
    
#mybatis 配置
#mybatis:
#  mapper-locations: classpath:resources/mappers/*.xml
#  config-location: classpath:mybatisConfig.xml
#  type-aliases-package: com.hpedu.web.core.*.pojo
#
##分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
##  returnPageInfo: check
